### ISSUE TITLE
project-template gulpfile.js need support git disabled updateset

### ISSUE THREAD

**Issue by gitlabbin** [bmoers/sn-cicd-example-v3#3]
In sn-cicd v3, allows disable git via `CICD_GIT_ENABLED=false`, 
but only  one gulpfile template `sn-cicd/lib/project-templates/gulpfile.js` for build, so it will fail the job.

Better provide two templates:
- gulpfile.git.js
- gulpfile.nogit.js

Need enhancement while copy the template file to repo, if git disabled then use an other gulpfile.

Thanks

**Comment by gitlabbin** [comment]
notice there is a `sn-cicd-example-v3/project-templates/read.me` for customisation,
will find out if this can be feasible for  git disable

**Comment by gitlabbin** [comment]
error when `CICD_GIT_ENABLED=false`

```
### Starting Task 'default'
[15:16:45] Starting 'default'...

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
	CICD Endpoint: https://localhost:8443
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 

Error: Commit ID not found. This seems not to be a git repository.
    at git.initialized.then (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/gulpfile.js:155:23)
    at tryCatcher (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/private/var/folders/cf/2kk1grls3x568v0dkdfv25km0000gn/T/git-root/3edb0566-5ee6-48cf-8f3e-340da525b341/node_modules/sn-project/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
### Task Ended 'default'
No config found for task 'default'

```
