### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by sash1kanth** [bmoers/sn-cicd-example-v3#4]
When I run example background script exactly as explained, I get following error 

request ended in error - StatusCode 0, ResponseMessage: The request failed: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure, Endpoint: https://<mac ip>:4443/run, RequestBody: [object Object]: no thrown error

Not sure whats going on wrong!

**Comment by sash1kanth** [comment]
I believe error gone once I changed the cicd server host name property to http://<ip>:8080/run. Code fail if I use that property as https://<ip-adress>:4443/run. 

Now the new error, I believe my credentials are right, but still couldn't make it to work. The host server throws errors 

result: undefined,
  error: undefined } Error: no auth mechanism defined

here is the stack trace
==============================
PROMISE JOB ERROR: Job 'projectSetup' { type: 'exe',
  name: 'projectSetup',
  options: 
   { build: { requestor: [Object] },
     atf: { updateSetOnly: false },
     updateSet: '47f69dcddb80330036ff7de03c961925',
     application: 
      { id: '19190fabdbebd300dfa9b94ffe96193e',
        name: 'CICD Integration',
        organization: 'company' },
     git: 
      { repository: 'sn-cicd-example-v3',
        remoteUrl: null,
        enabled: true,
        pullRequestEnabled: true },
     host: { name: 'https://dev49044.service-now.com' },
     master: { name: 'master', host: [Object] } },
  host: 'cala-am02059986',
  id: '809aeb98-e8be-4a2b-82d0-c4d75a55b967',
  emitter: { domain: null, _events: {}, _eventsCount: 2 },
  created: 1551842917634,
  completed: null,
  workerId: '/worker#pe1wllYEH-yqg6_CAAAD',
  result: undefined,
  error: undefined } Error: no auth mechanism defined

at Auth.onRequest (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request/lib/auth.js:132:32)
    at Request.auth (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request/request.js:1347:14)
    at Request.init (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request/request.js:378:10)
    at Request.RP$initInterceptor [as init] (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request-promise-core/configure/request2.js:45:29)
    at new Request (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request/request.js:127:8)
    at request (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request/index.js:53:10)
    at /Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request/index.js:100:12
    at /Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/sn-rest-client/index.js:115:20
    at /Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/sn-rest-client/index.js:64:16
    at tryCatcher (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/sn-rest-client/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/sn-rest-client/node_modules/bluebird/js/release/method.js:15:34
    at run (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/sn-rest-client/index.js:92:16)
    at Object.get (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/sn-rest-client/index.js:215:20)
    at Object.getUpdateSetDetails (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/sn-cicd/lib/snClient.js:73:23)
    at CICD.getUpdateSetDetails (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/sn-cicd/lib/cicd.js:460:23)
    at Promise.try.then (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/sn-cicd/lib/modules/project-setup.js:211:25)
    at tryCatcher (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)

**Comment by bmoers** [comment]
Are the credentials correct in the .env file?

at Promise.try.then (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/sn-cicd/lib/modules/project-setup.js:211:25)
the process is using CICD_CI_USER_NAME / PASSWORD to connect to config.host.name

**Comment by sash1kanth** [comment]
Here is the credentials section from my .env file. It has all properties filled (or did I miss any?)
I made those accounts as Admin, just to verify. Source and target have same accounts with same userid/password. Still get error, 

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# CREDENTIALS
#
# instance specific credentials can be set like
# CICD_[ATF]_[INSTANCENAME]_[TEST_USER_NAME]
# if not specified the default is used CICD_[ATF]_[TEST_USER_NAME]
CICD_ATF_TEST_USER_NAME=ATF-User
CICD_ATF_TEST_USER_PASSWORD=abc123

# example for instance specific credentials
#CICD_ATF_TEST_INSTANCENAME_USER_NAME=
#CICD_ATF_TEST_INSTANCENAME_USER_PASSWORD=

# user to load update-set form 'source' and 'master'
CICD_CI_USER_NAME=cd-user
CICD_CI_USER_PASSWORD=abc123

# example for instance specific credentials
#CICD_CI_INSTANCENAME_USER_NAME=CI-USER-NAME
#CICD_CI_INSTANCENAME_USER_PASSWORD=

# user to deploy update-set to 'target'
CICD_CD_USER_NAME=cd-user
CICD_CD_USER_PASSWORD=abc123

# example for instance specific credentials
#CICD_CD_INSTANCENAME_USER_NAME=CD-USER-NAME
#CICD_CD_INSTANCENAME_USER_PASSWORD=

**Comment by sash1kanth** [comment]
any issue with special characters like '-' in the user id?

**Comment by bmoers** [comment]
not that I know.
please log information in CICD.prototype.getUpdateSetDetails in node_modules/sn-cicd/lib/cicd.js
especially used here 
const client = self.getClient(config);

**Comment by sash1kanth** [comment]
It looks like the Process.env is returning as object but any dotwalk throwing error, where should I troubleshoot this? Should I rename example.env to something else? or could use any name including example.env? Currently its example.env

Here are the log messages, it shows process.env.[key] dotwalk throws undefined. Any idea?

[09:42:06.849] [LOG]   [60302]   The config update set pulled from config is >>>>>>> 47f69dcddb80330036ff7de03c961925
[09:42:06.850] [LOG]   [60302]  The Config Host is >>>> [object Object]
[09:42:06.850] [LOG]   [60302]  The Config Host  name is  >>>> https://dev49044.service-now.com
[09:42:06.850] [LOG]   [60302]  The Config self.settings.proxy  >>>> [object Object]
[09:42:06.850] [LOG]   [60302]  The Config username is >>>> undefined
[09:42:06.850] [LOG]   [60302]  The Config password is >>>> undefined
[09:42:06.851] [LOG]   [60302]  The Config process.env.CICD_GIT_DELETE_BRANCH_ON_MERGE is >>>> undefined
[09:42:06.851] [LOG]   [60302]  The Config appPrefix is >>>> undefined
[09:42:06.860] [LOG]   [60302]   The Client getUpdateSetDetails >>>>>>> [object Promise]

**Comment by sash1kanth** [comment]
I see two example.env files. One at root level -->sn-cicd-examplev3/emaple.env
second sn-cicd-emaplev3/node-modules/sn-cicd/example.env

which one should I be modifying? I have my key values on the first one. Even the case of second one used at runtime, it should still pull your example values like 'Admin' '********' right? 

if I had to review process.env file read, where would I be looking?

**Comment by sash1kanth** [comment]
Would you mind spending little time with me over WebEx? Just need 30
minutes of your time. Things started working as I start hardcoding
credentials in the script. But end up new errors.
Something is wrong. ServiceNow recommended us to explore CICD built by you.
for some reason, can't run a simple example. Great if you could pull little
time for me during your EOB. I'm from California, can join your last hour
during business.

**Comment by sash1kanth** [comment]
Hi Boris
I'm on Blue Jeans --> https://bluejeans.com/5555017804 if that doesn't
work, we would use hangouts or goto meeting.

Appreciate your time
Sashi Maddali

**Comment by makhan7** [comment]
I am having similar issues and can join you guys. please let me know if you will be doing go to meeting session @sash1kanth or we can tag up and resolve some of these issues.

**Comment by sash1kanth** [comment]
@makhan7 we could fix some of issues caused due to documentation. Boris I think is working onto fixing few other issues. Please get a fresh copy and let me know your errors. i would help to solve primary issues. I would include you in our next Test call with Boris.

**Comment by sash1kanth** [comment]
For me the basic flow working fine until Git versioning from the source instance.

**Comment by makhan7** [comment]
@bmoers @sash1kanth - I am able to spin up localhost:8080 and see the jobs running but don't see any update sets displayed under UpdateSet section. I might missed some credentials in .env file(it could be quick fix). Also, I am able to see my state changing to build when I marked update-sets to complete.

I can share my screen and go over it when you have a min on webex or can share the source code with you guys.

Thanks!

**Comment by bmoers** [comment]
Please run npm update in your local copy and have a look at the latest .env example file https://github.com/bmoers/sn-cicd-example-v3/blob/master/example.env 

Also make sure you have the latest version 1.3.10 of the CICD Integration app installed
https://github.com/bmoers/sn-cicd-integration

I'll post a new howto next week.

**Comment by makhan7** [comment]
Excellent!  I've deleted all the old repos and cloned two below urls into one CICD folder.. then ran npm install on the v3 
https://github.com/bmoers/sn-cicd-example-v3
https://github.com/bmoers/sn-cicd-integration

looking forward for the how to.

I will update my .env file and let you know the result..

Thank you so much @Bmoers for prompt response.

**Comment by bmoers** [comment]
@makhan7 @sash1kanth 
I have released the latest version of the CICD server today.
You find the latest version of the documentation of this example impl here:
https://github.com/bmoers/sn-cicd-example-v3

Please follow the steps on that page and let me know if you have questions.
I'll add a video asap.

**Comment by sash1kanth** [comment]
@bmoers I tried to checkout latest updates and try to follow new instructions. I couldn't follow these steps as I don't see UI actions on the Application page either by Button or related links

Install the example application
open the App /sys_app.do?sys_id=CICD%20Test%20Application
click on "Build this Application [CICD]"

I could see list of UI actions added, but they don't show up on the form to perform click. 
May I know what I miss? Added CICD Test Application update set and committed. But still don't see that build button.

**Comment by bmoers** [comment]
The UI actions only show up if you enable it.
Did you follow 
https://github.com/bmoers/sn-cicd-example-v3#configure-the-cicd-integration-in-servicenow
- [x] Show CICD UI action in scoped apps

**Comment by sash1kanth** [comment]
@bmoers Thanks that solved problem. However based on below instructions, you have a Test App to test it out or recommended to create Test Global App and add code underneath. I followed below instructions and clicked on Build this App

Install the example application
open the App /sys_app.do?sys_id=CICD%20Test%20Application
click on "Build this Application [CICD]"

I downloaded above App to Test it out. I clicked 'Build this Application' button

I see a new Update Set created with state 'build' but nothing happened after that. Does that 'Build this Application' UI action expected to trigger everything to move from source to target?

**Comment by sash1kanth** [comment]
I changed update set 'CICD Test Application – 1.0.0' from 'build' to 'Complete', save page refreshes as 'buid' again but no triggering of actions to initiate build process. 

Now I create another 'CICD Test Global Application', added one script include. 

1. I don't see [] option on the editor to add code comments
2. I clicked on Build this Application on the new Global App
3. System creates new Update Set with state 'build'

Nothing happens after that. No error message nor any process triggered.

**Comment by sash1kanth** [comment]
@bmoers I'm open for a call to run one end-to-end test case.

**Comment by bmoers** [comment]
Please check the logs in service now. 
Is the MID server up and running and validated?
Can the mid server reach the CICD server?
Is the CiCd server correctly set in service now?

**Comment by sash1kanth** [comment]
The URL to the local host is given 8080 now updated to 8443, which triggers the job. Now the latest error. Not sure whats wrong on repo side
=================
[17:20:47.534] [LOG]    [9547]   [/worker#BogsUd_cxTih5aybAAAG] project-setup : Git RemoteUrl set from ENV.CICD_GIT_HOST to 'x_0956_cicd_global.git'
[17:20:47.539] [LOG]    [9547]   [/worker#BogsUd_cxTih5aybAAAG] project-setup : Git RemoteUrl set from ENV.CICD_GIT_URL to 'https://github.com/x_0956_cicd_global'
[17:20:47.543] [LOG]    [9547]   [/worker#BogsUd_cxTih5aybAAAG] project-setup : Remove Dir '/Users/madds025/Documents/CICD/repos/ba98764b-ae7c-4b94-bd6e-009c519ca1dc' if exists
[17:20:47.551] [LOG]    [9547]   [/worker#BogsUd_cxTih5aybAAAG] project-setup : Create remote repository (if needed) 'x_0956_cicd_global'
[17:20:47.909] [ERROR]  [9547]   Somethings not right with the GitHub Access
[17:20:48.242] [ERROR]  [9547]   [/worker#BogsUd_cxTih5aybAAAG] PROMISE JOB ERROR: Job 'projectSetup' { type: 'exe',
  name: 'projectSetup',
  options: 
   { build: { requestor: [Object] },
     atf: { updateSetOnly: false },
     updateSet: '9850359ddb6833002fc1e04a4896190d',
     application: 
      { id: '3e185741db2433002fc1e04a489619ec',
        name: 'CICD Global Test App - Sashi',
        organization: 'company' },
     git: 
      { repository: 'x_0956_cicd_global',
        remoteUrl: null,
        enabled: true,
        pullRequestEnabled: true },
     host: { name: 'https://dev60131.service-now.com/' } },
  host: 'cala-am02059986',
  id: '20415cfd-41ff-4b30-a0ba-eda1736bd20b',
  emitter: { domain: null, _events: {}, _eventsCount: 2 },
  created: 1554078046979,
  completed: null,
  workerId: '/worker#BogsUd_cxTih5aybAAAG',
  result: undefined,
  error: undefined } { message: 'Bad credentials',
  documentation_url: 'https://developer.github.com/v3' }
[17:20:48.246] [LOG]    [9545]   /worker#BogsUd_cxTih5aybAAAG is done (/worker/done) with job: 20415cfd-41ff-4b30-a0ba-eda1736bd20b Type: exe
[17:20:48.246] [ERROR]  [9545]   Job failed on worker { id: '20415cfd-41ff-4b30-a0ba-eda1736bd20b',
  type: 'exe',
  host: 'cala-am02059986',
  platform: 'darwin',
  background: undefined } %j { name: 'StatusCodeError',
  statusCode: 401,
  message: '401 - {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}',
  error: 
   { message: 'Bad credentials',
     documentation_url: 'https://developer.github.com/v3' },
  options: 
   { method: 'GET',
     uri: 'https://api.github.com/repos/github-account-name/x_0956_cicd_global/hooks',
     json: true,
     auth: 
      { username: 'github-account-name',
        password: 'github-account-password/token',
        user: 'github-account-name',
        pass: 'github-account-password/token' },
     headers: { 'User-Agent': 'github-account-name' },
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: 
   { statusCode: 401,
     body: 
      { message: 'Bad credentials',
        documentation_url: 'https://developer.github.com/v3' },
     headers: 
      { date: 'Mon, 01 Apr 2019 00:20:50 GMT',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '83',
        connection: 'close',
        server: 'GitHub.com',
        status: '401 Unauthorized',
        'x-github-media-type': 'github.v3',
        'x-ratelimit-limit': '60',
        'x-ratelimit-remaining': '58',
        'x-ratelimit-reset': '1554081650',
        'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type',
        'access-control-allow-origin': '*',
        'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
        'x-frame-options': 'deny',
        'x-content-type-options': 'nosniff',
        'x-xss-protection': '1; mode=block',
        'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
        'content-security-policy': 'default-src \'none\'',
        'x-github-request-id': 'C590:2A0C:28632A5:30F35D3:5CA15962' },
     request: { uri: [Object], method: 'GET', headers: [Object] } },
  stack: 'StatusCodeError: 401 - {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}\n    at new StatusCodeError (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request-promise-core/lib/errors.js:32:15)\n    at Request.plumbing.callback (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request-promise-core/lib/plumbing.js:104:33)\n    at Request.RP$callback [as _callback] (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at Request.self.callback (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request/request.js:1161:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1055:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)' }
[17:20:48.251] [ERROR]  [9550]   { name: 'StatusCodeError',
  statusCode: 401,
  message: '401 - {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}',
  error: 
   { message: 'Bad credentials',
     documentation_url: 'https://developer.github.com/v3' },
  options: 
   { method: 'GET',
     uri: 'https://api.github.com/repos/github-account-name/x_0956_cicd_global/hooks',
     json: true,
     auth: 
      { username: 'github-account-name',
        password: 'github-account-password/token',
        user: 'github-account-name',
        pass: 'github-account-password/token' },
     headers: { 'User-Agent': 'github-account-name' },
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: 
   { statusCode: 401,
     body: 
      { message: 'Bad credentials',
        documentation_url: 'https://developer.github.com/v3' },
     headers: 
      { date: 'Mon, 01 Apr 2019 00:20:50 GMT',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '83',
        connection: 'close',
        server: 'GitHub.com',
        status: '401 Unauthorized',
        'x-github-media-type': 'github.v3',
        'x-ratelimit-limit': '60',
        'x-ratelimit-remaining': '58',
        'x-ratelimit-reset': '1554081650',
        'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type',
        'access-control-allow-origin': '*',
        'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
        'x-frame-options': 'deny',
        'x-content-type-options': 'nosniff',
        'x-xss-protection': '1; mode=block',
        'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
        'content-security-policy': 'default-src \'none\'',
        'x-github-request-id': 'C590:2A0C:28632A5:30F35D3:5CA15962' },
     request: { uri: [Object], method: 'GET', headers: [Object] } },
  stack: 'StatusCodeError: 401 - {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}\n    at new StatusCodeError (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request-promise-core/lib/errors.js:32:15)\n    at Request.plumbing.callback (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request-promise-core/lib/plumbing.js:104:33)\n    at Request.RP$callback [as _callback] (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at Request.self.callback (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request/request.js:1161:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1055:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)' }
[17:20:48.254] [LOG]    [9550]   setProgress build_failed
[17:20:48.254] [ERROR]  [9550]   context not correctly created
[17:20:48.255] [ERROR]  [9550]   CICD.prototype.addStep Error: addStep, no run instance found. State: run.run : failed
    at Promise.try (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/sn-cicd/lib/cicd.js:447:23)
    at tryCatcher (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/method.js:39:29)
    at CICD.addStep (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/sn-cicd/lib/cicd.js:442:27)
    at step (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/sn-cicd/lib/modules/run.js:22:21)
    at Promise.try.then (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/sn-cicd/lib/modules/run.js:56:20)
    at tryCatcher (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/madds025/Documents/CICD/sn-cicd-example-v3/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by bmoers** [comment]
The github credentials are not set. 
{ username: 'github-account-name',
password: 'github-account-password/token',

Please read the documentation carefully and also make sure you remove credentials from text which you paste here. 

If you think the documentation is not clear in some points, please let me know or raise a PR.

**Comment by makhan7** [comment]
@bmoers I followed your instructions step by step from here https://github.com/bmoers/sn-cicd-example-v3 and guess what! It works like a charm! I'm very excited! Thank you so much!

**Comment by sash1kanth** [comment]
@bmoers got time to run test cases one more time today. Everything worked well until update set complete. Change weren't deployed to Production with the following message

Pull request merged, but not deployment target environment specified.

I verified .env for target instance. Not sure which property controls it?

CICD_CD_DEPLOYMENT_TARGET is that one? I gave it the target instance name but why changes weren't deployed?

**Comment by bmoers** [comment]
@sash1kanth pleas let me know if you need further assistance or if I can close this issue.

CICD_CD_DEPLOYMENT_TARGET is the default target environment. e.g. all update sets of all dev environments will only be deployed to this env.

the recommended way is to use the source-target mapping as below
CICD_CD_DEPLOYMENT_TARGET_DEV12345=dev67890.service-now.com
CICD_CD_DEPLOYMENT_TARGET_DEV67890=devABCD.service-now.com

**Comment by sash1kanth** [comment]
Thanks @bmoers , it was my pleasure meeting you in person. We are good on this issue.
