### ISSUE TITLE
Getting issue while running ATF through CICD pipeline

### ISSUE THREAD

**Issue by mua32** [bmoers/sn-cicd-example-v3#8]
Facing below issue while running the ATF test case through CICD pipeline-

TypeError: describe is not a function
    at Object.<anonymous> (C:\temp\repos\ad8a6168-156f-46b6-9cb2-58c11c145e90\test\atf-wrapper.js:62:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\Temp\repos\ad8a6168-156f-46b6-9cb2-58c11c145e90\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Temp\repos\ad8a6168-156f-46b6-9cb2-58c11c145e90\node_modules\mocha\lib\mocha.js:331:14)
    at Mocha.run (C:\Temp\repos\ad8a6168-156f-46b6-9cb2-58c11c145e90\node_modules\mocha\lib\mocha.js:811:10)
    at Object.exports.singleRun (C:\Temp\repos\ad8a6168-156f-46b6-9cb2-58c11c145e90\node_modules\mocha\lib\cli\run-helpers.js:108:16)
    at exports.runMocha (C:\Temp\repos\ad8a6168-156f-46b6-9cb2-58c11c145e90\node_modules\mocha\lib\cli\run-helpers.js:142:13)
    at Object.exports.handler.argv [as handler] (C:\Temp\repos\ad8a6168-156f-46b6-9cb2-58c11c145e90\node_modules\mocha\lib\cli\run.js:292:3)
    at Object.runCommand (C:\Temp\repos\ad8a6168-156f-46b6-9cb2-58c11c145e90\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\Temp\repos\ad8a6168-156f-46b6-9cb2-58c11c145e90\node_modules\yargs\yargs.js:1087:28)
    at Object.parse (C:\Temp\repos\ad8a6168-156f-46b6-9cb2-58c11c145e90\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (C:\Temp\repos\ad8a6168-156f-46b6-9cb2-58c11c145e90\node_modules\mocha\lib\cli\cli.js:68:6)
    at Object.<anonymous> (C:\Temp\repos\ad8a6168-156f-46b6-9cb2-58c11c145e90\node_modules\mocha\bin\mocha:154:29)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by bmoers** [comment]
looks like the previous step where it runs `npm install` did not complete correctly (mocha is missing https://github.com/bmoers/sn-cicd/blob/master/lib/project-templates/atf-wrapper.js#L62)
please check in the logs for any messages related to this.
you can also check manually and go to C:\temp\repos\ad8a6168-156f-46b6-9cb2-58c11c145e90 and run npm install

**Comment by mua32** [comment]
Hi Boris,

Thanks for the response.Unfortunately I am still facing the same issue.
I have tried running the commands-
npm install
npm update
I tried running npm install in C:\temp\repos\ad8a6168-156f-46b6-9cb2-58c11c145e90 but still facing the same issue.

**Comment by bmoers** [comment]
Does „npm install“ log any errors?

**Comment by mua32** [comment]
Getting below logs while running npm install-

npm WARN sn-cicd-example@3.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 3300 packages in 6.515s
found 1 high severity vulnerability

**Comment by bmoers** [comment]
What version of node and npm are you using?
The gulp process requires to run node < 12.
Run `node -v` and `npm -v`

**Comment by mua32** [comment]
node version is v10.16.3
npm version is 6.9.0

It is trying to search the file in this directory-"C:\Temp\repos\fab61ed0-b503-43ae-8b45-0e407bc309a7\node_modules\yargs\yargs.js" .

But when I went to the directory I cant find folder named node_module in -"C:\Temp\repos\fab61ed0-b503-43ae-8b45-0e407bc309a7".

Below is the log that is getting displayed-

Upload Results doc Upload successful!  Server responded with: File uploaded!
Remove file 'C:\Users\SHUVAR~1\AppData\Local\Temp\9cce7b9a-ddc6-4e7c-82aa-8e4070c5fefc\doc.zip'
Upload Results lint Upload successful!  Server responded with: File uploaded!
Remove file 'C:\Users\SHUVAR~1\AppData\Local\Temp\9cce7b9a-ddc6-4e7c-82aa-8e4070c5fefc\lint.zip'
Remove file 'C:\Users\SHUVAR~1\AppData\Local\Temp\9cce7b9a-ddc6-4e7c-82aa-8e4070c5fefc\doc'
Remove file 'C:\Users\SHUVAR~1\AppData\Local\Temp\9cce7b9a-ddc6-4e7c-82aa-8e4070c5fefc\lint'
C:\Temp\repos\fab61ed0-b503-43ae-8b45-0e407bc309a7\node_modules\yargs\yargs.js:1163
      else throw err
           ^

TypeError: describe is not a function

**Comment by bmoers** [comment]
the node_nodules directory gets deleted at the end to save disk space.
please 'cd C:\Temp\repos\fab61ed0-b503-43ae-8b45-0e407bc309a7\' , delete the 'package-lock.json' file, run 'npm install' in that directory and paste the whole output here.
my guess is that something with mocha or mochawesome is not correct as they require yargs
thanks

**Comment by mua32** [comment]
Below is the output received after running npm install-

npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> core-js@2.6.9 postinstall C:\Temp\repos\992a9ee2-0841-4702-bb3f-874443e17ef4\node_modules\core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm notice created a lockfile as package-lock.json. You should commit this file.
added 738 packages from 1188 contributors and audited 2526 packages in 155.91s
found 7 vulnerabilities (1 low, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by bmoers** [comment]
Looks ok so far.

Would you mind and 
- delete the github repo
- restart the CICD server
- run the whole process again
and send the full logs and the .env file to the email in my profile?

Thanks
Boris
